### PR TITLE
Fixed errors when using against lts-7.4

### PR DESCRIPTION
**Pull request by seanhess**
Hi, thanks for the great work. I've fixed a few errors that came up when I attempted to use 0.3.1 against stackage lts-7.4. See the individual commits for details. Specifically, I fixed an error with String vs Text for Monad Logger and deprecation warnings for http conduit. 

I also added a stack.yaml file to help with local development.

### CODE REVIEW

**Comment by gregwebs** [comment]
Thanks! Would u like to maintain this package? I am not using rollbar right now

**Comment by seanhess** [comment]
I probably won't be using it very actively. Can you keep up with any PRs I find and republish? If so let's wait and see how much I use it. If not, then sure I can take over.

**Comment by seanhess** [comment]
@gregwebs What do you think? Will you merge and republish this?

**Comment by sjalowoi** [comment]
Hi @gregwebs and @seanhess ,
i'm interested too for the merge of the pull request and the republish. 
I'm too newbie in haskell for the moment to maintain the package.
Anyway, thanks for the job ! 
Sylvain

**Comment by seanhess** [comment]
@gregwebs I'd be happy to maintain the package. Will you transfer this repo to me? Do you know how to grant publish rights on hackage?

**Comment by spl** [comment]
@seanhess: I would also be fine with you maintaining the package. And it seems I have the abilities to transfer the repository on GitHub and to add you to the maintainer group on Hackage. Since @gregwebs has already suggested so, I'll assume he agrees with this.

Please give me your Hackage user name.

**Comment by jetaggart** [comment]
@spl: We've started using this branch in production. I'd be happy to take this over as maintainer if you're still open to it.

**Comment by spl** [comment]
@jetaggart No problem. Better to have a maintainer than let it sit idle. To which GitHub user/organization should I transfer it and which Hackage user should be added to the maintainer group?

**Comment by jetaggart** [comment]
@spl: Awesome, thank you. GitHub org == azara, Hackage == azara

**Comment by spl** [comment]
@jetaggart: I've added you as a collaborator on GitHub and `azara` as a maintainer on Hackage. You'll have to do the transfer of the GitHub repository yourself, since you are a member of the azara organization.

**Comment by jetaggart** [comment]
Thank you, all set. I appreciate it!

**Pull request merged**
